language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r demo-webservice *
  - mkdir -p deploy
  - mv demo-webservice.zip deploy/demo-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: demo-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_acess_key: $AWS_SECRET_KEY
    bucket: demo-webservice-build
    key: demo-webservice.zip #빌드 파일을 압축해서 전달
    bundle_type: zip
    application: demo-webservice #웹콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: demo-webservice-group #웹콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - zeeyon.c@gmail.com
